# Generated by Django 4.0.5 on 2022-10-19 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condominium', '0001_initial'),
        ('building', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('require_maintenance', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='building.building')),
                ('condominium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='condominium.condominium')),
            ],
            options={
                'verbose_name': 'Installation',
                'verbose_name_plural': 'Installations',
                'ordering': ('-created',),
            },
        ),
    ]
